blank_issues_enabled: false
contact_links:
  - name: 🔒 Privacy Policy / Политика конфиденциальности
    url: https://internetova.github.io/my-pets-app/privacy-policy-en.html
    about: How the app handles your data / Как приложение обращается с вашими данными.
